import type { Config, Theme, ThemeName } from './schema.js';

export const DEFAULTS: Config = {
  nvidia_api_key: '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',
  style: 'default',
  theme: 'default',
  search_enabled: true,
  memory_enabled: true,
  welcome_enabled: true,
  max_turns_headless: 10,
  temperature: 0.72,
  top_p: 0.95,
  max_tokens: 8192,
};

export const THEMES: Record<ThemeName, Theme> = {
  default: {
    accent: 'cyan',
    muted: 'gray',
    border: 'gray',
    success: 'green',
    error: 'red',
    warning: 'yellow',
    info: 'blue',
    user_label: 'cyan',
    ai_label: 'cyan',
    code_dim: 'dim',
  },
  dark: {
    accent: 'white',
    muted: 'gray',
    border: 'dim',
    success: 'green',
    error: 'red',
    warning: 'yellow',
    info: 'blue',
    user_label: 'white',
    ai_label: 'white',
    code_dim: 'dim',
  },
  midnight: {
    accent: 'white',
    muted: '#666',
    border: '#333',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffff00',
    info: '#00ffff',
    user_label: 'white',
    ai_label: 'white',
    code_dim: 'dim',
  },
  forest: {
    accent: 'green',
    muted: '#4a6b4a',
    border: '#2d4a2d',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffff00',
    info: '#00ffff',
    user_label: 'green',
    ai_label: 'green',
    code_dim: 'dim',
  },
  rose: {
    accent: 'magenta',
    muted: '#6b4a55',
    border: '#4a2d35',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffff00',
    info: '#00ffff',
    user_label: 'magenta',
    ai_label: 'magenta',
    code_dim: 'dim',
  },
  ocean: {
    accent: 'blue',
    muted: '#4a5b6b',
    border: '#2d4a5a',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffff00',
    info: '#00ffff',
    user_label: 'blue',
    ai_label: 'blue',
    code_dim: 'dim',
  },
  gold: {
    accent: 'yellow',
    muted: '#6b6b4a',
    border: '#4a4a20',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffff00',
    info: '#00ffff',
    user_label: 'yellow',
    ai_label: 'yellow',
    code_dim: 'dim',
  },
  sepia: {
    accent: '#c8a96e',
    muted: '#8a7a5a',
    border: '#6a5a4a',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffff00',
    info: '#00ffff',
    user_label: '#c8a96e',
    ai_label: '#c8a96e',
    code_dim: 'dim',
  },
  hacker: {
    accent: '#00ff00',
    muted: '#006600',
    border: '#003300',
    success: '#00ff00',
    error: '#ff0000',
    warning: '#ffff00',
    info: '#00ffff',
    user_label: '#00ff00',
    ai_label: '#00ff00',
    code_dim: 'dim',
  },
};
